# Generated by Django 4.0.6 on 2022-07-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_seller",
            field=models.BooleanField(default=False),
        ),
    ]
